### ISSUE TITLE
Unexpected Application Error!

### ISSUE THREAD

**Issue by OSpoon** [1111mp/nvm-desktop#3]
OS：MacOS 12.5 (21G72)

Cannot destructure property 'version' of 't[0]' as it is undefined.

```
TypeError: Cannot destructure property 'version' of 't[0]' as it is undefined.
    at file:///Applications/nvm-desktop.app/Contents/Resources/app.asar/dist/renderer/renderer.js:2:1023803
    at Ei (file:///Applications/nvm-desktop.app/Contents/Resources/app.asar/dist/renderer/renderer.js:2:818578)
    at Es (file:///Applications/nvm-desktop.app/Contents/Resources/app.asar/dist/renderer/renderer.js:2:875433)
    at xc (file:///Applications/nvm-desktop.app/Contents/Resources/app.asar/dist/renderer/renderer.js:2:864585)
    at bc (file:///Applications/nvm-desktop.app/Contents/Resources/app.asar/dist/renderer/renderer.js:2:864513)
    at vc (file:///Applications/nvm-desktop.app/Contents/Resources/app.asar/dist/renderer/renderer.js:2:864376)
    at ic (file:///Applications/nvm-desktop.app/Contents/Resources/app.asar/dist/renderer/renderer.js:2:861183)
    at ac (file:///Applications/nvm-desktop.app/Contents/Resources/app.asar/dist/renderer/renderer.js:2:859735)
    at C (file:///Applications/nvm-desktop.app/Contents/Resources/app.asar/dist/renderer/renderer.js:2:919573)
    at MessagePort.P (file:///Applications/nvm-desktop.app/Contents/Resources/app.asar/dist/renderer/renderer.js:2:920105)
```

**Comment by 1111mp** [comment]
Can you give more information about the error?
For example, What or when you do something. It‘s better that have some screenshots.
